"""Generate compat/process/android_ids.inc from the pinned
android_filesystem_config.h, as bionic's fs_config_generator derives its
android_ids table: AID_FOO_BAR becomes "foo_bar"; range markers and the
AID_APP/AID_USER bases are not names."""
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[1]
header = root / "_aosp/system/core/libcutils/include/private/android_filesystem_config.h"
skip = {"AID_APP", "AID_USER", "AID_USER_OFFSET", "AID_APP_START", "AID_APP_END",
        "AID_OVERFLOWUID"}
entries = []
for match in re.finditer(r"^#define (AID_[A-Z0-9_]+)\s+(\d+)", header.read_text(), re.M):
    name, value = match.groups()
    if name in skip or name.endswith("_START") or name.endswith("_END"):
        continue
    entries.append((name[4:].lower(), int(value)))
lines = ["// Generated by tools/generate-android-ids.py from",
         "// system/core/libcutils/include/private/android_filesystem_config.h.",
         "// Do not edit."]
lines += [f'{{"{name}", {value}}},' for name, value in entries]
out = root / "compat/process/android_ids.inc"
out.write_text("\n".join(lines) + "\n")
print(f"android ids: {len(entries)} -> {out}")
