#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Darwin ART contributors
"""Render notices from the locked Cargo graph and locally cached crate sources."""

import argparse
import hashlib
import json
from pathlib import Path
import subprocess


def render(root):
    metadata = json.loads(subprocess.check_output(
        ["cargo", "metadata", "--offline", "--locked", "--format-version", "1"],
        cwd=root,
    ))
    packages = sorted(
        (p for p in metadata["packages"] if p["source"]),
        key=lambda p: (p["name"], p["version"], p["source"]),
    )
    lock_hash = hashlib.sha256((root / "Cargo.lock").read_bytes()).hexdigest()
    chunks = [
        "Rust dependency license and notice documents\n",
        "Generated by darwin-art/tools/update-rust-license-notices.py.\n",
        "Includes the resolved workspace graph, including build/test dependencies.\n",
        "These upstream documents are reproduced verbatim, not relicensed.\n",
        "This is not the notice inventory of native libraries or a compiled app.\n",
        f"Cargo.lock SHA-256: {lock_hash}\n",
    ]
    for package in packages:
        source_root = Path(package["manifest_path"]).parent
        documents = {
            path for path in source_root.iterdir()
            if path.is_file() and path.name.upper().startswith(
                ("LICENSE", "COPYING", "NOTICE", "COPYRIGHT")
            )
        }
        if package.get("license_file"):
            documents.add(source_root / package["license_file"])
        if not documents:
            raise SystemExit(f"No license documents found for {package['id']}")
        chunks.extend([
            "\n" + "=" * 72 + "\n",
            f"Package: {package['name']} {package['version']}\n",
            f"Declared license: {package.get('license') or 'see license file'}\n",
            f"Source: {package['source']}\n",
            f"Repository: {package.get('repository') or 'not declared'}\n",
        ])
        for path in sorted(documents):
            data = path.read_bytes()
            chunks.extend([
                f"\n--- {path.relative_to(source_root)} ---\n",
                f"SHA-256: {hashlib.sha256(data).hexdigest()}\n\n",
                data.decode("utf-8"),
                "\n",
            ])
    return "".join(chunks)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail on notice drift")
    args = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    target = root.parent / "licensing/rust-dependencies.txt"
    text = render(root)
    if args.check:
        if not target.is_file() or target.read_bytes() != text.encode("utf-8"):
            raise SystemExit("Rust notices are missing or stale; run this tool without --check")
        print("Rust dependency notices match the locked workspace")
    else:
        target.write_bytes(text.encode("utf-8"))
        print(f"Updated {target}")


if __name__ == "__main__":
    main()
