"""Generates the Rust crates of the vendor HALs' stable AIDL interfaces the
way Soong's rust_aidl does (the aidl-gen node of `cargo aim`, docs/build.md).

For each interface of hal/sources.lock, the SDK `aidl` compiles its frozen
API against the frozen APIs of its imports (`-I`, transitively), and the
crate glue follows aidl_rust_glue.py: the package tree under `aidl`, and a
`mangled` namespace that re-exports the imported crates' `mangled`, which
the generated code refers to. Each interface's checked-in manifest
(hal/aidl/<package>/Cargo.toml) must depend on exactly the crates of its
imports.

Files are rewritten only when their content changes, so cargo rebuilds only
what changed.

Usage: vendor_hal_aidl.py AIDL APIS OUT MANIFESTS ENTRY...
  APIS/<package>/<version> holds each checked frozen API; the crate of
  <package> V<version> goes to OUT/<package>-V<version>; ENTRY is an
  AIDL_INTERFACES line of hal/sources.lock.
"""

import os
import shutil
import subprocess
import sys
import tomllib


def fail(message):
    sys.exit(f"vendor_hal_aidl: {message}")


def crate(package):
    return package.replace(".", "_")


class Interfaces:
    def __init__(self, apis, entries):
        self.apis = apis
        self.versions = {}
        self.imports = {}
        for entry in entries:
            package, version, _, _, imports = entry.split("|")
            self.versions[package] = int(version)
            self.imports[package] = [i for i in imports.split(",") if i]
        for package, imports in self.imports.items():
            for spec in imports:
                name, _, version = spec.rpartition("-V")
                if self.versions.get(name) != int(version):
                    fail(f"{package} imports {spec}, which sources.lock does not list")

    def api_dir(self, package):
        return f"{self.apis}/{package}/{self.versions[package]}"

    def direct(self, package):
        return [spec.rpartition("-V")[0] for spec in self.imports[package]]

    def transitive(self, package, seen=None):
        seen = set() if seen is None else seen
        for name in self.direct(package):
            if name not in seen:
                seen.add(name)
                self.transitive(name, seen)
        return sorted(seen)


def glue(package, version, files, imports):
    tree = {}
    for f in files:
        node = tree
        *dirs, name = f[: -len(".aidl")].split("/")
        for part in dirs:
            node = node.setdefault(part, {})
        node[name] = None
    lines = [
        f"// Generated by tools/lib/vendor_hal_aidl.py for {package} V{version},",
        "// as Soong's aidl_rust_glue.py (Soong builds it with --cap-lints allow).",
        "#![allow(warnings)]",
        "pub use binder;",
        "pub mod aidl {",
    ]
    mangled = []

    def emit(node, path):
        pad = "  " * len(path)
        for name, child in node.items():
            if child is None:
                # Relative to lib.rs's directory plus the enclosing inline
                # modules, i.e. aidl/<package path>.
                lines.append(f'{pad}#[path = "{name}.rs"]')
                lines.append(f"{pad}pub mod {name};")
                mangled.append(f"  pub use super::{'::'.join(path + [name])}::mangled::*;")
            else:
                lines.append(f"{pad}pub mod {name} {{")
                emit(child, path + [name])
                lines.append(f"{pad}}}")

    emit(tree, ["aidl"])
    lines.append("}")
    lines.append("pub mod mangled {")
    lines += mangled
    lines += [f"  pub(crate) use {crate(i)}::mangled::*;" for i in imports]
    lines.append("}")
    return "\n".join(lines) + "\n"


def sync(new, old):
    """Makes `old` a copy of `new`, writing only files that differ."""
    wanted = set()
    for base, _, names in os.walk(new):
        for name in names:
            rel = os.path.relpath(os.path.join(base, name), new)
            wanted.add(rel)
            with open(os.path.join(new, rel), "rb") as f:
                data = f.read()
            target = os.path.join(old, rel)
            if os.path.exists(target):
                with open(target, "rb") as f:
                    if f.read() == data:
                        continue
            os.makedirs(os.path.dirname(target), exist_ok=True)
            with open(target, "wb") as f:
                f.write(data)
    for base, _, names in os.walk(old):
        for name in names:
            rel = os.path.relpath(os.path.join(base, name), old)
            if rel not in wanted:
                os.remove(os.path.join(old, rel))


def generate(aidl, interfaces, package, out, manifests):
    version = interfaces.versions[package]
    imports = interfaces.direct(package)
    with open(f"{manifests}/{package}/Cargo.toml", "rb") as f:
        manifest = tomllib.load(f)
    deps = {d for d in manifest.get("dependencies", {}) if d.startswith("android_")}
    if deps != {crate(i) for i in imports}:
        fail(
            f"hal/aidl/{package}/Cargo.toml depends on {sorted(deps)}, "
            f"but V{version} imports {sorted(crate(i) for i in imports)}"
        )
    if manifest["package"]["version"].split(".")[0] != str(version):
        fail(f"hal/aidl/{package}/Cargo.toml: version is not {version}.x")
    src = interfaces.api_dir(package)
    files = sorted(
        os.path.relpath(os.path.join(base, name), src)
        for base, _, names in os.walk(src)
        for name in names
        if name.endswith(".aidl")
    )
    with open(f"{src}/.hash") as f:
        # Soong compiles in the last line (`tail -1`); earlier lines hash
        # earlier edits of the same frozen version.
        api_hash = f.read().split()[-1]
    # The generated files quote the command line, so it has only relative
    # paths and no temporary names: the output depends on the inputs alone.
    includes = [
        a
        for i in interfaces.transitive(package)
        for a in ("-I", os.path.relpath(interfaces.api_dir(i), src))
    ]
    new = f"{out}/.staging"
    shutil.rmtree(new, ignore_errors=True)
    subprocess.run(
        ["aidl", "--lang=rust", "--structured", "--stability=vintf",
         f"--version={version}", f"--hash={api_hash}",
         "-I", ".", *includes, "-o", os.path.relpath(f"{new}/aidl", src), *files],
        executable=aidl,
        cwd=src,
        check=True,
    )
    with open(f"{new}/lib.rs", "w") as f:
        f.write(glue(package, version, files, imports))
    sync(new, f"{out}/{package}-V{version}")
    shutil.rmtree(new)


def main():
    aidl, apis, out, manifests, *entries = sys.argv[1:]
    interfaces = Interfaces(apis, entries)
    for package in interfaces.versions:
        generate(aidl, interfaces, package, out, manifests)
        print(f"generated {package} V{interfaces.versions[package]}")


if __name__ == "__main__":
    main()
