// Generated by tools/gen-art-shell-commands.py from android-16.0.0_r1; do not edit.
pub const SUPPORTED: &[&str] = &[
    "compile",
    "reconcile-secondary-dex-files",
    "force-dex-opt",
    "bg-dexopt-job",
    "cancel-bg-dexopt-job",
    "delete-dexopt",
    "dump-profiles",
    "snapshot-profile",
    "art",
];
