//! `native-inventory`: every native method the pinned, unmodified Android 16
//! boot and system server jars declare, as the checked-in list each JNI owner
//! is accounted against (crates/darwin-art-native-inventory/generated/android16-natives.tsv).

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use darwin_art_native_inventory::{NativeMethod, dex_natives};

use crate::Result;
use crate::support::command_output;

const OUTPUT: &str = "crates/darwin-art-native-inventory/generated/android16-natives.tsv";
const BOOT_JARS: &str = "_build/android16-bootclasspath-original";
const SERVER_JARS: &str = "_build/android16-systemserverclasspath-original";
const SERVER_LOCK: &str = "upstream/android16-systemserverclasspath.lock";

/// Every original jar with its device path: the boot jars as extracted from
/// the image, then the system server jars the lock pins.
fn jars(root: &Path) -> Result<Vec<(String, PathBuf)>> {
    let mut jars = Vec::new();
    let boot = root.join(BOOT_JARS);
    let mut pending = vec![boot.clone()];
    while let Some(directory) = pending.pop() {
        for entry in fs::read_dir(&directory)? {
            let path = entry?.path();
            if path.is_dir() {
                pending.push(path);
            } else if path.extension().is_some_and(|extension| extension == "jar") {
                let device = format!("/{}", path.strip_prefix(&boot)?.display());
                jars.push((device, path));
            }
        }
    }
    let lock = fs::read_to_string(root.join(SERVER_LOCK))?;
    for line in lock.lines() {
        let fields: Vec<_> = line.split_whitespace().collect();
        if let [_, "classpath" | "standalone", device] = fields[..] {
            let path = root.join(SERVER_JARS).join(device.trim_start_matches('/'));
            jars.push((device.to_owned(), path));
        }
    }
    if jars.is_empty() {
        return Err(format!("no original jars under {BOOT_JARS}").into());
    }
    jars.sort();
    Ok(jars)
}

fn jar_natives(jar: &Path) -> Result<Vec<NativeMethod>> {
    let entries = command_output(Command::new("/usr/bin/unzip").arg("-Z1").arg(jar))?;
    let mut natives = Vec::new();
    for entry in entries.lines() {
        if !(entry.starts_with("classes") && entry.ends_with(".dex")) {
            continue;
        }
        let output = Command::new("/usr/bin/unzip")
            .arg("-p")
            .arg(jar)
            .arg(entry)
            .output()?;
        if !output.status.success() {
            return Err(format!("cannot read {entry} from {}", jar.display()).into());
        }
        natives.extend(
            dex_natives(&output.stdout)
                .map_err(|error| format!("{}!{entry}: {error}", jar.display()))?,
        );
    }
    Ok(natives)
}

pub(crate) fn native_inventory(root: &Path) -> Result<()> {
    let mut lines = Vec::new();
    for (device, jar) in jars(root)? {
        if !jar.is_file() {
            return Err(format!("missing original jar {}", jar.display()).into());
        }
        for native in jar_natives(&jar)? {
            lines.push(format!("{device}\t{native}"));
        }
    }
    lines.sort();
    lines.dedup();
    let mut text = String::from(
        "# Native methods of the pinned Android 16 boot and system server jars\n\
         # (unmodified originals). Generated by `art-bootstrap native-inventory`.\n\
         # Fields: JAR CLASS METHOD SIGNATURE\n",
    );
    for line in &lines {
        text.push_str(line);
        text.push('\n');
    }
    let output = root.join(OUTPUT);
    fs::create_dir_all(output.parent().unwrap())?;
    fs::write(&output, text)?;
    println!("native-inventory: {} natives -> {OUTPUT}", lines.len());
    Ok(())
}
