[package]
license.workspace = true
name = "darwin-art-profile"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
darwin-art-engine-sys = { path = "../darwin-art-engine-sys" }
darwin-art-binder-device = { path = "../darwin-art-binder-device" }
darwin-art-scm-transfer = { path = "../darwin-art-scm-transfer" }
libc = "0.2"

[lib]
name = "darwin_art_profile"
path = "src/lib.rs"

[[bin]]
name = "darwin-artd"
path = "src/bin/darwin-artd.rs"

[[bin]]
name = "darwin-artctl"
path = "src/bin/darwin-artctl.rs"
