use super::SigningScan;
use crate::package::{installer::environment::capture_visibility_checked,libraries::Policy,owner::{seinfo,usage::Usage},pkg::AndroidPackage,scan::LoadedPackage,scan_snapshot::Store,settings::{Package,Settings},sign::SigningDetails,system_config::SystemConfig};
use std::{collections::BTreeMap,sync::{Arc,Barrier},cell::Cell};
fn fixture()->Arc<Store>{
 let packages=vec![Package{name:"target.fixture".into(),app_id:10101,code_path:"/data/app/target".into(),version_code:1,domain_set_id:Some("00000000-0000-0000-0000-000000000001".into()),..Default::default()},Package{name:"background.fixture".into(),app_id:10102,code_path:"/data/app/background".into(),version_code:1,domain_set_id:Some("00000000-0000-0000-0000-000000000002".into()),..Default::default()}];
 let settings=Settings{packages,..Default::default()};let mut owner=SigningScan::new(&SystemConfig::default(),&settings,29).unwrap();
 for setting in &settings.packages{let signing=SigningDetails{unknown:false,signatures:vec![vec![1]],scheme_version:2,public_keys:Some(vec![]),..SigningDetails::unknown()};let package=AndroidPackage{feature_flag_state:Some(vec![]),package_name:setting.name.clone(),path:Some(setting.code_path.clone()),base_apk_path:Some(format!("{}/base.apk",setting.code_path)),uid:setting.app_id,version_code:1,target_sdk_version:35,signing_details:signing.package_details().unwrap(),..Default::default()};owner.loaded.insert(setting.name.clone(),Arc::new(LoadedPackage::new(package,signing).unwrap()));owner.scanned_users.insert(setting.name.clone(),[(0,Default::default())].into());}
 owner.assign_seinfo_at_boot(&seinfo::Policy::unread(),&mut|package|Ok(package.target_sdk_version)).unwrap();owner.complete_library_dependencies(&|_,_|Ok(Policy::pinned(true))).unwrap();let usage=Usage::new(["target.fixture","background.fixture"]);owner.complete_runtime_at_boot(&usage,BTreeMap::new()).unwrap();owner.settings.shared_users=owner.identities.ordered_shared_users().unwrap().into_iter().map(|(name,group)|crate::package::settings::SharedUser{name:name.into(),app_id:group.app_id,flags:0,signatures:group.signatures.clone()}).collect();Arc::new(Store::new(owner,usage).unwrap())
}
fn publish_state(store:&Store,name:&str,protected:bool){let prior=store.capture();let mut owner=prior.owner().clone();let mut state=owner.scanned_user_states(name).unwrap()[&0].clone();if protected{state.enabled=2;}else{state.hidden=true;}owner.set_user_state(name,0,state).unwrap();let mut usage=prior.usage().clone();usage.notify(name,1,91);owner.update_replica_usage(prior.usage(),&usage).unwrap();store.publish(&prior,owner,usage).unwrap();}
#[test]
fn interleaved_visibility_recaptures_latest_policy_and_preserves_original_base(){
 let store=fixture();let base=store.capture();let start=Arc::new(Barrier::new(2));let done=Arc::new(Barrier::new(2));let writer=store.clone();let a=start.clone();let b=done.clone();let thread=std::thread::spawn(move||{a.wait();publish_state(&writer,"background.fixture",false);b.wait();});let calls=Cell::new(0);
 let values=capture_visibility_checked(&base,&store,&["target.fixture".into()],||Ok(vec![0]),|setting,users|{assert_eq!(setting.app_id,10101);assert_eq!(users,[0]);let captured=store.capture();calls.set(calls.get()+1);let hidden=captured.owner().scanned_user_states("background.fixture").unwrap()[&0].hidden;if calls.get()==1{start.wait();done.wait();}Ok((captured.version(),if hidden{vec![0,0]}else{vec![0,1,10102]}))}).unwrap();thread.join().unwrap();assert_eq!(calls.get(),2);assert_eq!(values,[vec![0,0]]);assert!(!base.owner().scanned_user_states("background.fixture").unwrap()[&0].hidden);assert!(store.capture().owner().scanned_user_states("background.fixture").unwrap()[&0].hidden);assert_eq!(store.capture().usage().times("background.fixture").unwrap()[1],91);
}
#[test]
fn interleaved_protected_target_change_rejects_instead_of_reusing_visibility(){let store=fixture();let base=store.capture();let calls=Cell::new(0);let result=capture_visibility_checked(&base,&store,&["target.fixture".into()],||Ok(vec![0]),|_,_|{let captured=store.capture();calls.set(calls.get()+1);publish_state(&store,"target.fixture",true);Ok((captured.version(),vec![0,1,10102]))});assert!(result.is_err());assert_eq!(calls.get(),1);assert_eq!(store.capture().owner().scanned_user_states("target.fixture").unwrap()[&0].enabled,2);}
#[test]
fn stale_original_visibility_capability_is_never_accepted(){let store=fixture();let base=store.capture();let calls=Cell::new(0);let result=capture_visibility_checked(&base,&store,&["target.fixture".into()],||Ok(vec![0]),|_,_|{calls.set(calls.get()+1);Ok((base.version()+1,vec![0,1,10102]))});assert!(result.is_err());assert_eq!(calls.get(),8);assert!(Arc::ptr_eq(&base,&store.capture()));}
#[test]
fn protected_code_change_rejects_before_calling_visibility_owner(){
 let store=fixture();let base=store.capture();let mut owner=base.owner().clone();owner.settings.packages.iter_mut().find(|p|p.name=="target.fixture").unwrap().code_path="/data/app/target-replaced".into();let package=&mut Arc::make_mut(owner.loaded.get_mut("target.fixture").unwrap()).package;package.path=Some("/data/app/target-replaced".into());package.base_apk_path=Some("/data/app/target-replaced/base.apk".into());owner.assign_seinfo_at_boot(&seinfo::Policy::unread(),&mut|package|Ok(package.target_sdk_version)).unwrap();owner.complete_library_dependencies(&|_,_|Ok(Policy::pinned(true))).unwrap();crate::package::installer::permission_prepare::complete_candidate_runtime(&mut owner,&base,base.usage()).unwrap();store.publish(&base,owner,base.usage().clone()).unwrap();let calls=Cell::new(0);let result=capture_visibility_checked(&base,&store,&["target.fixture".into()],||Ok(vec![0]),|_,_|{calls.set(calls.get()+1);Ok((store.capture().version(),vec![0,0]))});assert!(result.is_err());assert_eq!(calls.get(),0);assert_eq!(store.capture().owner().settings.packages.iter().find(|p|p.name=="target.fixture").unwrap().code_path,"/data/app/target-replaced");
}

#[test]
fn identical_package_inventory_from_another_store_epoch_is_rejected(){let original=fixture();let foreign=fixture();let base=original.capture();assert_eq!(base.owner().settings,foreign.capture().owner().settings);let calls=Cell::new(0);let result=capture_visibility_checked(&base,&foreign,&["target.fixture".into()],||Ok(vec![0]),|_,_|{calls.set(calls.get()+1);Ok((foreign.capture().version(),vec![0,0]))});assert!(result.unwrap_err().message.contains("lineage"));assert_eq!(calls.get(),0);}
