[workspace]
members = [
    "crates/aim-android-image",
    "crates/aim-android-init",
    "crates/aim-guest-init",
    "crates/aim-binder-driver",
    "crates/aim-binder-host",
    "crates/aim-host-audio",
    "crates/aim-host-bluetooth",
    "crates/aim-host-camera",
    "crates/aim-host-display",
    "crates/aim-host-gpu",
    "crates/aim-host-health",
    "crates/aim-host-location",
    "crates/aim-host-sensors",
    "crates/aim-hostcall",
    "crates/aim-linux-abi",
    "tools/android-image-extract",
]
resolver = "2"

[workspace.package]
license = "Apache-2.0"
