[package]
license.workspace = true
name = "bionic-fs-facade"
version = "0.1.0"
edition = "2024"
publish = false
build = "build.rs"

[dependencies]
libc = "0.2"
aim-elf-loader = { path = "../../crates/aim-elf-loader" }
aim-fs-broker = { path = "../../crates/aim-fs-broker" }
aim-prefix = { path = "../../crates/aim-prefix" }
