[package]
license.workspace = true
name = "android-image-extract"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
path = "src/lib.rs"

[[bin]]
name = "android-image-extract"
path = "src/main.rs"

[dependencies]
crc32fast = "1.5"
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }
sha2.workspace = true
