// Generated by tools/gen-art-shell-commands.py from android-16.0.0_r1; do not edit.
package com.android.server.pm;

final class NativeArtShellCommands {
    private static final java.util.Set<String> SUPPORTED = java.util.Set.of(
    "compile",
    "reconcile-secondary-dex-files",
    "force-dex-opt",
    "bg-dexopt-job",
    "cancel-bg-dexopt-job",
    "delete-dexopt",
    "dump-profiles",
    "snapshot-profile",
    "art"
    );
    private NativeArtShellCommands() {}
    static boolean supports(String command) { return command != null && SUPPORTED.contains(command); }
}
