use crate::{AuthorityEpoch, EndpointId, ProcessEpoch, TransferKey};

/// The two provider protocols that may carry an endpoint capability.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum AttributeKind {
    Binder,
    Scm,
}

/// A binding is an opaque, exact description of one provider-owned transfer.
/// It is compared as a whole; no individual field is trusted in isolation.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum Binding {
    Binder {
        source_connection: u64,
        transfer: u64,
        ordinal: u64,
        object_offset: u64,
    },
    Scm {
        transfer_key: TransferKey,
        ordinal: u64,
    },
}

impl Binding {
    pub(crate) fn kind(self) -> AttributeKind {
        match self {
            Self::Binder { .. } => AttributeKind::Binder,
            Self::Scm { .. } => AttributeKind::Scm,
        }
    }

    pub(crate) fn valid_for(self, authority: AuthorityEpoch) -> bool {
        match self {
            Self::Binder {
                source_connection,
                transfer,
                ..
            } => source_connection != 0 && transfer != 0,
            Self::Scm { transfer_key, .. } => {
                transfer_key.authority == authority && transfer_key.ticket != 0
            }
        }
    }
}

/// A record returned by pair registration. The grants are handles to the two
/// opposite endpoints, not additional carrier ownership objects.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct RegisteredPair {
    pub endpoint_a: EndpointId,
    pub endpoint_b: EndpointId,
    pub holder_a: HolderGrant,
    pub holder_b: HolderGrant,
}

/// A non-forgeable (outside this crate) grant identifier bound to one process
/// incarnation and one endpoint. Copying this value does not create a holder.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct HolderGrant {
    pub(crate) authority: AuthorityEpoch,
    pub(crate) id: u128,
    pub(crate) process: ProcessEpoch,
    pub(crate) endpoint: EndpointId,
}

impl HolderGrant {
    pub fn id(self) -> u128 {
        self.id
    }

    pub fn process(self) -> ProcessEpoch {
        self.process
    }

    pub fn endpoint(self) -> EndpointId {
        self.endpoint
    }
}

/// Delegation identifiers are generated by the registry and never accepted
/// as a caller-supplied minting input.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct DelegationId(pub(crate) u128);

impl DelegationId {
    pub fn get(self) -> u128 {
        self.0
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DelegationState {
    Pending,
    /// Authentic deposited-but-unrouted state; not a placeholder process.
    Committed {
        receiver: Option<ProcessEpoch>,
    },
    Claimed {
        receiver: ProcessEpoch,
        holder_id: u128,
    },
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct DelegationRecord {
    pub id: DelegationId,
    pub endpoint: EndpointId,
    pub source: ProcessEpoch,
    pub binding: Binding,
    pub state: DelegationState,
}

/// The authorizer is intentionally a distinct API object. It is held by the
/// daemon-side code that has proved the successful Binder TAKE or SCM receive;
/// holder grants cannot authorize their own delivery.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct TrustedAuthorizer {
    pub(crate) authority: AuthorityEpoch,
}

/// Result of claiming a committed delivery. The new grant preserves the
/// delegated payload endpoint side; transport-side opposite-endpoint proof is
/// performed by the trusted provider before authorization.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ClaimedDelivery {
    pub delegation: DelegationId,
    pub grant: HolderGrant,
    pub endpoint: EndpointId,
    pub receiver: ProcessEpoch,
}

/// Explicit cleanup is required after the provider's bound bundle settles.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum DeliveryDisposition {
    Finished,
    Aborted,
}
