// Compile-only pinned image API, android-16.0.0_r1; checked by image linkage.
package com.android.server.pm;
import android.content.ComponentName;
import android.content.Intent;
import android.content.IntentFilter;
import android.content.pm.ActivityInfo;
import android.content.pm.ApplicationInfo;
import android.content.pm.ComponentInfo;
import android.content.pm.InstallSourceInfo;
import android.content.pm.InstrumentationInfo;
import android.content.pm.KeySet;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.content.pm.ParceledListSlice;
import android.content.pm.ProcessInfo;
import android.content.pm.ProviderInfo;
import android.content.pm.ResolveInfo;
import android.content.pm.ServiceInfo;
import android.content.pm.SharedLibraryInfo;
import android.content.pm.SigningDetails;
import android.content.pm.UserInfo;
import android.content.pm.VersionedPackage;
import android.os.UserHandle;
import android.util.ArrayMap;
import android.util.ArraySet;
import android.util.Pair;
import android.util.SparseArray;
import android.util.proto.ProtoOutputStream;
import com.android.server.pm.pkg.AndroidPackage;
import com.android.server.pm.pkg.PackageStateInternal;
import com.android.server.pm.pkg.SharedUserApi;
import com.android.server.pm.resolution.ComponentResolverApi;
import com.android.server.pm.snapshot.PackageDataSnapshot;
import com.android.server.utils.WatchedArrayMap;
import com.android.server.utils.WatchedLongSparseArray;
import java.io.FileDescriptor;
import java.io.PrintWriter;
import java.util.List;
import java.util.Set;
public interface Computer extends PackageDataSnapshot {
    public int getVersion();
    public Computer use();
    public default int getUsed() { throw new RuntimeException("stub"); }
    public List<ResolveInfo> queryIntentActivitiesInternal(Intent intent, String resolvedType, long flags, long privateResolveFlags, int filterCallingUid, int callingPid, int userId, boolean resolveForStart, boolean allowDynamicSplits);
    public List<ResolveInfo> queryIntentActivitiesInternal(Intent intent, String resolvedType, long flags, int filterCallingUid, int userId);
    public List<ResolveInfo> queryIntentActivitiesInternal(Intent intent, String resolvedType, long flags, int userId);
    public List<ResolveInfo> queryIntentServicesInternal(Intent intent, String resolvedType, long flags, int userId, int callingUid, int callingPid, boolean includeInstantApps, boolean resolveForStart);
    public ActivityInfo getActivityInfo(ComponentName component, long flags, int userId);
    public ActivityInfo getActivityInfoInternal(ComponentName component, long flags, int filterCallingUid, int userId);
    public AndroidPackage getPackage(String packageName);
    public AndroidPackage getPackage(int uid);
    public ApplicationInfo getApplicationInfo(String packageName, long flags, int userId);
    public ApplicationInfo getApplicationInfoInternal(String packageName, long flags, int filterCallingUid, int userId);
    public ComponentName getDefaultHomeActivity(int userId);
    public ComponentName getHomeActivitiesAsUser(List<ResolveInfo> allHomeCandidates, int userId);
    public CrossProfileDomainInfo getCrossProfileDomainPreferredLpr(Intent intent, String resolvedType, long flags, int sourceUserId, int parentUserId);
    public Intent getHomeIntent();
    public List<CrossProfileIntentFilter> getMatchingCrossProfileIntentFilters(Intent intent, String resolvedType, int userId);
    public List<ResolveInfo> applyPostResolutionFilter(List<ResolveInfo> resolveInfos, String ephemeralPkgName, boolean allowDynamicSplits, int filterCallingUid, boolean resolveForStart, int userId, Intent intent);
    public PackageInfo getPackageInfo(String packageName, long flags, int userId);
    public PackageInfo getPackageInfoInternal(String packageName, long versionCode, long flags, int filterCallingUid, int userId);
    public String[] getAllAvailablePackageNames();
    public PackageStateInternal getPackageStateInternal(String packageName);
    public PackageStateInternal getPackageStateInternal(String packageName, int callingUid);
    public PackageStateInternal getPackageStateFiltered(String packageName, int callingUid, int userId);
    public ParceledListSlice<PackageInfo> getInstalledPackages(long flags, int userId);
    public ResolveInfo createForwardingResolveInfoUnchecked(WatchedIntentFilter filter, int sourceUserId, int targetUserId);
    public ServiceInfo getServiceInfo(ComponentName component, long flags, int userId);
    public SharedLibraryInfo getSharedLibraryInfo(String name, long version);
    public String getInstantAppPackageName(int callingUid);
    public String resolveInternalPackageName(String packageName, long versionCode);
    public String[] getPackagesForUid(int uid);
    public UserInfo getProfileParent(int userId);
    public boolean canViewInstantApps(int callingUid, int userId);
    public boolean isCallerSameApp(String packageName, int uid);
    public boolean isCallerSameApp(String packageName, int uid, boolean resolveIsolatedUid);
    public boolean isImplicitImageCaptureIntentAndNotSetByDpc(Intent intent, int userId, String resolvedType, long flags);
    public boolean isInstantApp(String packageName, int userId);
    public boolean isInstantAppInternal(String packageName, int userId, int callingUid);
    public boolean shouldFilterApplication(PackageStateInternal ps, int callingUid, int userId);
    public boolean shouldFilterApplicationIncludingUninstalled(PackageStateInternal ps, int callingUid, int userId);
    public int checkUidPermission(String permName, int uid);
    public int getPackageUidInternal(String packageName, long flags, int userId, int callingUid);
    public long updateFlagsForResolve(long flags, int userId, int callingUid, boolean wantInstantApps, boolean isImplicitImageCaptureIntentAndNotSetByDpc);
    public void enforceCrossUserOrProfilePermission(int callingUid, int userId, boolean requireFullPermission, boolean checkShell, String message);
    public void enforceCrossUserPermission(int callingUid, int userId, boolean requireFullPermission, boolean checkShell, String message);
    public SigningDetails getSigningDetails(String packageName);
    public SigningDetails getSigningDetails(int uid);
    public boolean filterAppAccess(AndroidPackage pkg, int callingUid, int userId);
    public boolean filterAppAccess(String packageName, int callingUid, int userId, boolean filterUninstalled);
    public boolean filterAppAccess(int uid, int callingUid);
    public void dump(int type, FileDescriptor fd, PrintWriter pw, DumpState dumpState);
    public PackageManagerService.FindPreferredActivityBodyResult findPreferredActivityInternal(Intent intent, String resolvedType, long flags, List<ResolveInfo> query, boolean always, boolean removeMatches, boolean debug, int userId, boolean queryMayBeFiltered);
    public ResolveInfo findPersistentPreferredActivity(Intent intent, String resolvedType, long flags, List<ResolveInfo> query, boolean debug, int userId);
    public PreferredIntentResolver getPreferredActivities(int userId);
    public ArrayMap<String, ? extends PackageStateInternal> getPackageStates();
    public ArrayMap<String, ? extends PackageStateInternal> getDisabledSystemPackageStates();
    public ArraySet<String> getNotifyPackagesForReplacedReceived(String[] packages);
    public int getPackageStartability(boolean safeMode, String packageName, int callingUid, int userId);
    public boolean isPackageAvailable(String packageName, int userId);
    public boolean isApexPackage(String packageName);
    public String[] currentToCanonicalPackageNames(String[] names);
    public String[] canonicalToCurrentPackageNames(String[] names);
    public int[] getPackageGids(String packageName, long flags, int userId);
    public int getTargetSdkVersion(String packageName);
    public boolean activitySupportsIntentAsUser(ComponentName resolveComponentName, ComponentName component, Intent intent, String resolvedType, int userId);
    public ActivityInfo getReceiverInfo(ComponentName component, long flags, int userId);
    public ParceledListSlice<SharedLibraryInfo> getSharedLibraries(String packageName, long flags, int userId);
    public boolean canRequestPackageInstalls(String packageName, int callingUid, int userId, boolean throwIfPermNotDeclared);
    public boolean isInstallDisabledForPackage(String packageName, int uid, int userId);
    public Pair<List<VersionedPackage>, List<Boolean>> getPackagesUsingSharedLibrary(SharedLibraryInfo libInfo, long flags, int callingUid, int userId);
    public ParceledListSlice<SharedLibraryInfo> getDeclaredSharedLibraries(String packageName, long flags, int userId);
    public ProviderInfo getProviderInfo(ComponentName component, long flags, int userId);
    public ArrayMap<String, String> getSystemSharedLibraryNamesAndPaths();
    public PackageStateInternal getPackageStateForInstalledAndFiltered(String packageName, int callingUid, int userId);
    public int checkSignatures(String pkg1, String pkg2, int userId);
    public int checkUidSignatures(int uid1, int uid2);
    public int checkUidSignaturesForAllUsers(int uid1, int uid2);
    public boolean hasSigningCertificate(String packageName, byte[] certificate, int type);
    public boolean hasUidSigningCertificate(int uid, byte[] certificate, int type);
    public List<String> getAllPackages();
    public String getNameForUid(int uid);
    public String[] getNamesForUids(int[] uids);
    public int getUidForSharedUser(String sharedUserName);
    public int getFlagsForUid(int uid);
    public int getPrivateFlagsForUid(int uid);
    public boolean isUidPrivileged(int uid);
    public String[] getAppOpPermissionPackages(String permissionName, int userId);
    public ParceledListSlice<PackageInfo> getPackagesHoldingPermissions(String[] permissions, long flags, int userId);
    public List<ApplicationInfo> getInstalledApplications(long flags, int userId, int callingUid, boolean forceAllowCrossUser);
    public ProviderInfo resolveContentProvider(String name, long flags, int userId, int callingUid);
    public ProviderInfo resolveContentProviderForUid(String name, long flags, int userId, int filterCallingUid);
    public ProviderInfo getGrantImplicitAccessProviderInfo(int recipientUid, String visibleAuthority);
    public void querySyncProviders(boolean safeMode, List<String> outNames, List<ProviderInfo> outInfo);
    public ParceledListSlice<ProviderInfo> queryContentProviders(String processName, int uid, long flags, String metaDataKey);
    public InstrumentationInfo getInstrumentationInfoAsUser(ComponentName component, int flags, int userId);
    public ParceledListSlice<InstrumentationInfo> queryInstrumentationAsUser(String targetPackage, int flags, int userId);
    public List<PackageStateInternal> findSharedNonSystemLibraries(PackageStateInternal pkgSetting);
    public boolean getApplicationHiddenSettingAsUser(String packageName, int userId);
    public boolean isPackageSuspendedForUser(String packageName, int userId) throws PackageManager.NameNotFoundException;
    public boolean isPackageQuarantinedForUser(String packageName, int userId) throws PackageManager.NameNotFoundException;
    public boolean isPackageStoppedForUser(String packageName, int userId) throws PackageManager.NameNotFoundException;
    public boolean isSuspendingAnyPackages(String suspendingPackage, int suspendingUserId, int targetUserId);
    public ParceledListSlice<IntentFilter> getAllIntentFilters(String packageName);
    public boolean getBlockUninstallForUser(String packageName, int userId);
    public String getInstallerPackageName(String packageName, int userId);
    public InstallSourceInfo getInstallSourceInfo(String packageName, int userId);
    public int getApplicationEnabledSetting(String packageName, int userId);
    public int getComponentEnabledSetting(ComponentName component, int callingUid, int userId);
    public int getComponentEnabledSettingInternal(ComponentName component, int callingUid, int userId);
    public boolean isComponentEffectivelyEnabled(ComponentInfo componentInfo, UserHandle userHandle);
    public boolean isApplicationEffectivelyEnabled(String packageName, UserHandle userHandle);
    public KeySet getKeySetByAlias(String packageName, String alias);
    public KeySet getSigningKeySet(String packageName);
    public boolean isPackageSignedByKeySet(String packageName, KeySet ks);
    public boolean isPackageSignedByKeySetExactly(String packageName, KeySet ks);
    public SparseArray<int[]> getVisibilityAllowLists(String packageName, int[] userIds);
    public int[] getVisibilityAllowList(String packageName, int userId);
    public boolean canQueryPackage(int callingUid, String targetPackageName);
    public int getPackageUid(String packageName, long flags, int userId);
    public boolean canAccessComponent(int callingUid, ComponentName component, int userId);
    public boolean isCallerInstallerOfRecord(AndroidPackage pkg, int callingUid);
    public int getInstallReason(String packageName, int userId);
    public boolean[] canPackageQuery(String sourcePackageName, String[] targetPackageNames, int userId);
    public boolean canForwardTo(Intent intent, String resolvedType, int sourceUserId, int targetUserId);
    public List<ApplicationInfo> getPersistentApplications(boolean safeMode, int flags);
    public String[] getSharedUserPackagesForPackage(String packageName, int userId);
    public CharSequence getHarmfulAppWarning(String packageName, int userId);
    public String[] filterOnlySystemPackages(String[] pkgNames);
    public List<AndroidPackage> getPackagesForAppId(int appId);
    public int getUidTargetSdkVersion(int uid);
    public ArrayMap<String, ProcessInfo> getProcessesForUid(int uid);
    public boolean getBlockUninstall(int userId, String packageName);
    public WatchedArrayMap<String, WatchedLongSparseArray<SharedLibraryInfo>> getSharedLibraries();
    public Pair<PackageStateInternal, SharedUserApi> getPackageOrSharedUser(int appId);
    public SharedUserApi getSharedUser(int sharedUserAppIde);
    public ArraySet<PackageStateInternal> getSharedUserPackages(int sharedUserAppId);
    public ComponentResolverApi getComponentResolver();
    public PackageStateInternal getDisabledSystemPackage(String packageName);
    public ResolveInfo getInstantAppInstallerInfo();
    public WatchedArrayMap<String, Integer> getFrozenPackages();
    public void checkPackageFrozen(String packageName);
    public ComponentName getInstantAppInstallerComponent();
    public void dumpPermissions(PrintWriter pw, String packageName, ArraySet<String> permissionNames, DumpState dumpState);
    public void dumpPackages(PrintWriter pw, String packageName, ArraySet<String> permissionNames, DumpState dumpState, boolean checkin);
    public void dumpKeySet(PrintWriter pw, String packageName, DumpState dumpState);
    public void dumpSharedUsers(PrintWriter pw, String packageName, ArraySet<String> permissionNames, DumpState dumpState, boolean checkin);
    public void dumpSharedUsersProto(ProtoOutputStream proto);
    public void dumpPackagesProto(ProtoOutputStream proto);
    public void dumpSharedLibrariesProto(ProtoOutputStream protoOutputStream);
    public List<? extends PackageStateInternal> getVolumePackages(String volumeUuid);
    public UserInfo[] getUserInfos();
    public ArrayMap<String, ? extends SharedUserApi> getSharedUsers();
}
