package dev.darwinart.runtime.pm;

import android.content.Intent;
import android.content.IntentFilter;
import android.content.pm.ActivityInfo;
import android.content.pm.ApplicationInfo;
import android.content.pm.ComponentInfo;
import android.content.pm.PackageInfo;
import android.content.pm.ProviderInfo;
import android.content.pm.ResolveInfo;
import android.content.pm.ServiceInfo;
import com.android.internal.pm.parsing.PackageInfoCommonUtils;
import com.android.internal.pm.pkg.component.ParsedActivity;
import com.android.internal.pm.pkg.component.ParsedIntentInfo;
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Framework package DTOs for installed packages, generated by the original
 * AOSP PackageInfoCommonUtils from the parsed package.
 *
 * <p>Only per-install state that PackageManagerService keeps in its
 * PackageSetting (uid, code paths, data and native directories, installed
 * flag) comes from the profile's install ledger, and it is applied to every
 * generated ApplicationInfo. Booting PMS (#30) moves that state into its
 * Settings.</p>
 */
public final class InstalledPackageInfos {
    // ActivityManagerService.STOCK_PM_FLAGS.
    public static final long STOCK_PM_FLAGS = 0x400; // GET_SHARED_LIBRARY_FILES
    // PackageManager query flags used here.
    private static final long MATCH_DEFAULT_ONLY = 0x00010000L;
    private static final long GET_RESOLVED_FILTER = 0x00000040L;
    private static final long GET_PERMISSIONS = 0x00001000L;
    private static final long GET_ACTIVITIES = 0x00000001L;
    private static final long GET_SERVICES = 0x00000004L;
    private static final long GET_PROVIDERS = 0x00000008L;
    private static final long GET_URI_PERMISSION_PATTERNS = 0x00000800L;
    private static final long MATCH_DIRECT_BOOT_AWARE = 0x00080000L;
    private static final long MATCH_DIRECT_BOOT_UNAWARE = 0x00040000L;
    // Android user 0 only; the ledger allocates app ids for that user.
    private static final int USER_SYSTEM = 0;

    private InstalledPackageInfos() {}

    public static ApplicationInfo applicationInfo(String packageName, String record, long flags) {
        InstalledPackageParser.Parsed parsed = InstalledPackageParser.parse(packageName, record);
        return parsed == null ? null : generate(parsed, flags).applicationInfo;
    }

    public static PackageInfo packageInfo(String packageName, String record, long flags) {
        InstalledPackageParser.Parsed parsed = InstalledPackageParser.parse(packageName, record);
        return parsed == null ? null : generate(parsed, flags);
    }

    /** Service lookups for system services, backed by the installed-package ledger. */
    public static ServiceResolver serviceResolver(PackageRecords.Source packages) {
        return component -> {
            String packageName = component.getPackageName();
            String record = packages.resolveInstalledPackage(packageName);
            return record == null ? null
                    : service(packageName, record, component.getClassName(), STOCK_PM_FLAGS);
        };
    }

    /** True when the package's manifest requests {@code permission} (uses-permission). */
    public static boolean requestsPermission(String packageName, String record,
            String permission) {
        PackageInfo info = packageInfo(packageName, record, GET_PERMISSIONS);
        if (info == null || info.requestedPermissions == null) return false;
        for (String requested : info.requestedPermissions) {
            if (requested.equals(permission)) return true;
        }
        return false;
    }

    /** An activity or activity-alias declared by the package, by class name. */
    public static ActivityInfo activity(String packageName, String record, String className,
            long flags) {
        InstalledPackageParser.Parsed parsed = InstalledPackageParser.parse(packageName, record);
        if (parsed == null || className == null) return null;
        return named(generate(parsed, flags | GET_ACTIVITIES).activities, className);
    }

    /** The package's first MAIN/LAUNCHER activity, as a launcher resolves it. */
    public static ActivityInfo launchActivity(String packageName, String record) {
        Intent intent = new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER)
                .setPackage(packageName);
        List<ResolveInfo> resolved = queryIntentActivities(packageName, record, intent, null,
                STOCK_PM_FLAGS);
        return resolved == null || resolved.isEmpty() ? null : resolved.get(0).activityInfo;
    }

    public static ServiceInfo service(String packageName, String record, String className,
            long flags) {
        InstalledPackageParser.Parsed parsed = InstalledPackageParser.parse(packageName, record);
        if (parsed == null || className == null) return null;
        return named(generate(parsed, flags | GET_SERVICES).services, className);
    }

    public static ProviderInfo provider(String packageName, String record, String className,
            long flags) {
        InstalledPackageParser.Parsed parsed = InstalledPackageParser.parse(packageName, record);
        if (parsed == null || className == null) return null;
        return named(generate(parsed, flags | GET_PROVIDERS).providers, className);
    }

    /**
     * The providers ActivityManagerService installs in {@code processName} at
     * bindApplication: ContentProviderHelper.generateApplicationProvidersLocked
     * queries STOCK_PM_FLAGS | GET_URI_PERMISSION_PATTERNS, and
     * ComponentResolver.queryProviders keeps the process's providers ordered
     * by descending initOrder.
     */
    public static List<ProviderInfo> processProviders(String packageName, String record,
            String processName) {
        List<ProviderInfo> result = new ArrayList<>();
        InstalledPackageParser.Parsed parsed = InstalledPackageParser.parse(packageName, record);
        if (parsed == null || processName == null) return result;
        ProviderInfo[] providers = generate(parsed,
                STOCK_PM_FLAGS | GET_URI_PERMISSION_PATTERNS | GET_PROVIDERS).providers;
        if (providers == null) return result;
        for (ProviderInfo provider : providers) {
            if (processName.equals(provider.processName)) result.add(provider);
        }
        // Stable sort keeps declaration order among equal initOrder.
        Collections.sort(result, (a, b) -> Integer.compare(b.initOrder, a.initOrder));
        return result;
    }

    /**
     * Activities of one package whose intent filters match {@code intent}, in
     * ComponentResolver order (priority, then declaration). MATCH_DEFAULT_ONLY
     * requires CATEGORY_DEFAULT in the matching filter.
     */
    public static List<ResolveInfo> queryIntentActivities(String packageName, String record,
            Intent intent, String resolvedType, long flags) {
        InstalledPackageParser.Parsed parsed = InstalledPackageParser.parse(packageName, record);
        if (parsed == null) return new ArrayList<>();
        ActivityInfo[] generated = generate(parsed, flags | GET_ACTIVITIES).activities;
        List<ResolveInfo> result = new ArrayList<>();
        for (ParsedActivity activity : parsed.pkg.getActivities()) {
            ActivityInfo activityInfo = named(generated, activity.getName());
            // Filtered out by the query flags (for example a disabled component).
            if (activityInfo == null) continue;
            for (ParsedIntentInfo intentInfo : activity.getIntents()) {
                IntentFilter filter = intentInfo.getIntentFilter();
                int match = filter.match(intent.getAction(),
                        resolvedType != null ? resolvedType : intent.getType(),
                        intent.getScheme(), intent.getData(), intent.getCategories(),
                        "PackageManager");
                if (match < 0) continue;
                if ((flags & MATCH_DEFAULT_ONLY) != 0
                        && !filter.hasCategory(Intent.CATEGORY_DEFAULT)) {
                    continue;
                }
                ResolveInfo info = new ResolveInfo();
                info.activityInfo = activityInfo;
                info.match = match;
                info.priority = filter.getPriority();
                info.isDefault = filter.hasCategory(Intent.CATEGORY_DEFAULT);
                if ((flags & GET_RESOLVED_FILTER) != 0) info.filter = filter;
                result.add(info);
                break;
            }
        }
        // Stable sort keeps declaration order among equal priorities.
        Collections.sort(result, (a, b) -> Integer.compare(b.priority, a.priority));
        return result;
    }

    /**
     * PackageInfoCommonUtils.generate with the installed state applied to the
     * package and every component's ApplicationInfo. As for an unlocked user,
     * a query naming neither direct-boot match flag matches both.
     */
    private static PackageInfo generate(InstalledPackageParser.Parsed parsed, long flags) {
        if ((flags & (MATCH_DIRECT_BOOT_AWARE | MATCH_DIRECT_BOOT_UNAWARE)) == 0) {
            flags |= MATCH_DIRECT_BOOT_AWARE | MATCH_DIRECT_BOOT_UNAWARE;
        }
        PackageInfo info = PackageInfoCommonUtils.generate(parsed.pkg, flags, USER_SYSTEM);
        if (info == null) {
            throw new IllegalStateException("No PackageInfo for " + parsed.installed.packageName);
        }
        applyInstalledState(info.applicationInfo, parsed.installed);
        for (ComponentInfo[] components : new ComponentInfo[][] {
                info.activities, info.receivers, info.services, info.providers}) {
            if (components == null) continue;
            for (ComponentInfo component : components) {
                if (component.applicationInfo != info.applicationInfo) {
                    applyInstalledState(component.applicationInfo, parsed.installed);
                }
            }
        }
        return info;
    }

    private static <T extends ComponentInfo> T named(T[] components, String className) {
        if (components == null) return null;
        for (T component : components) {
            if (className.equals(component.name)) return component;
        }
        return null;
    }

    /** PackageSetting-owned state: uid, code paths, data and native directories. */
    private static void applyInstalledState(ApplicationInfo info,
            InstalledPackageRecord installed) {
        if (info == null) return;
        // An unregistered legacy record keeps an unknown uid rather than root.
        info.uid = installed.appId;
        info.sourceDir = installed.baseApk;
        info.publicSourceDir = installed.baseApk;
        // Apps still receive the ledger's code paths until they get the
        // /data/app mount themselves (#35).
        info.splitSourceDirs = hostPaths(info.splitSourceDirs);
        info.splitPublicSourceDirs = hostPaths(info.splitPublicSourceDirs);
        info.dataDir = installed.dataDirectory();
        setHiddenString(info, "credentialProtectedDataDir", info.dataDir);
        info.deviceProtectedDataDir = "/data/user_de/0/" + installed.packageName;
        info.nativeLibraryDir = installed.nativeLibraryDirectory();
        info.flags |= ApplicationInfo.FLAG_INSTALLED;
    }

    private static String[] hostPaths(String[] paths) {
        if (paths == null) return null;
        String[] result = new String[paths.length];
        for (int i = 0; i < paths.length; i++) {
            result[i] = InstalledPackageRecord.hostCodePath(paths[i]);
        }
        return result;
    }

    private static void setHiddenString(ApplicationInfo info, String name, String value) {
        try {
            Field field = ApplicationInfo.class.getDeclaredField(name);
            field.setAccessible(true);
            field.set(info, value);
        } catch (ReflectiveOperationException error) {
            throw new IllegalStateException("ApplicationInfo." + name + " is unavailable", error);
        }
    }
}
