#!/usr/bin/env python3
"""Derive the native/Java ART command policy from the pinned original PM shell.

Usage: tools/gen-art-shell-commands.py --source ORIGINAL_SOURCE [--check]
No input is fetched or modified. Generated output is checked in; normal builds
need no original Java source. --check rejects input or output policy drift.
"""
import argparse
import hashlib
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent
LOCK = ROOT / "upstream/art-shell-commands.lock"
RUST = ROOT / "crates/aim-services/src/package/art_shell_commands.rs"
JAVA = ROOT / "java/device-services/src/com/android/server/pm/NativeArtShellCommands.java"

def derive(source):
    pin = dict(line.split("=", 1) for line in LOCK.read_text().splitlines()
               if line and not line.startswith("#"))
    data = source.read_bytes()
    if hashlib.sha256(data).hexdigest() != pin["SOURCE_SHA256"]:
        raise ValueError("original PM shell source differs from its pin")
    match = re.search(r"private\s+static\s+final\s+Set<String>\s+ART_SERVICE_COMMANDS\s*=\s*Set\.of\((.*?)\);", data.decode(), re.S)
    if not match:
        raise ValueError("pinned ART_SERVICE_COMMANDS declaration missing")
    commands = re.findall(r'"([^"\\]+)"', match.group(1))
    if not commands or len(set(commands)) != len(commands):
        raise ValueError("empty or duplicate original ART policy")
    quoted = ",\n".join(f'    "{command}"' for command in commands)
    rust = f'// Generated by tools/gen-art-shell-commands.py from {pin["AOSP_TAG"]}; do not edit.\n'
    rust += f'pub const SUPPORTED: &[&str] = &[\n{quoted},\n];\n'
    java = f'// Generated by tools/gen-art-shell-commands.py from {pin["AOSP_TAG"]}; do not edit.\n'
    java += 'package com.android.server.pm;\n\nfinal class NativeArtShellCommands {\n'
    java += f'    private static final java.util.Set<String> SUPPORTED = java.util.Set.of(\n{quoted}\n    );\n'
    java += '    private NativeArtShellCommands() {}\n'
    java += '    static boolean supports(String command) { return command != null && SUPPORTED.contains(command); }\n}\n'
    return {RUST: rust, JAVA: java}, commands

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        outputs, commands = derive(args.source)
        for path, text in outputs.items():
            if args.check:
                if not path.is_file() or path.read_text() != text:
                    raise ValueError(f"generated ART policy differs: {path.relative_to(ROOT)}")
            else:
                path.write_text(text)
    except (OSError, ValueError) as error:
        parser.error(str(error))
    print(f"ART_SHELL_POLICY_PIN_PASS commands={len(commands)} mode={'check' if args.check else 'generate'}")

if __name__ == "__main__":
    main()
